# A name for the workflow, which will be displayed in the Actions tab of your GitHub repository.
name: Build KisanHub Android App

# Configure the trigger for this workflow.
on:
  # Run on pushes to the 'main' branch.
  push:
    branches: [ "main" ]
  # Run on pull requests targeting the 'main' branch.
  pull_request:
    branches: [ "main" ]
  # Allow manual triggering from the GitHub Actions UI.
  workflow_dispatch:

# Define the jobs to be executed.
jobs:
  # A single job named 'build-apk'.
  build-apk:
    # Use the latest version of Ubuntu as the runner environment.
    runs-on: ubuntu-latest

    # Define the sequence of steps for this job.
    steps:
      # Step 1: Check out your repository code.
      # This is a mandatory first step for the workflow to access your project files.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java Development Kit (JDK).
      # Android builds require a specific version of the JDK. Version 17 is standard for modern Android.
      # This step also configures caching for Gradle dependencies to speed up subsequent builds.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Step 3: Make the Gradle Wrapper executable.
      # The 'gradlew' file needs execute permissions to run. This is a crucial step.
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Build the debug APK.
      # The 'assembleDebug' task compiles the code and packages it into an APK file.
      # This single command handles the entire build process.
      - name: Build debug APK
        run: ./gradlew assembleDebug

      # Step 5: Upload the generated APK as an artifact.
      # This makes the APK file available for download from the workflow summary page.
      # Uses the corrected and current 'v4' of the action.
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          # The name of the artifact in the GitHub UI.
          name: KisanHub-debug.apk
          # The path to the file to be uploaded. This is the standard output path for a debug APK.
          path: app/build/outputs/apk/debug/app-debug.apk
          # The number of days to retain the artifact before it's automatically deleted.
          retention-days: 5
